[package]
name = "assert_cli"
version = "0.3.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]
repository = "https://github.com/killercup/assert_cli.git"
homepage = "https://github.com/killercup/assert_cli"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "http://killercup.github.io/assert_cli/"
description = "Test CLI Applications."
build = "build.rs"

[features]
default = []
dev = ["clippy"]

[dependencies]
colored = "1.4"
difference = "1.0"
error-chain = "0.10.0"
clippy = {version = "*", optional = true}

[build-dependencies]
skeptic = "0.5"

[dev-dependencies]
skeptic = "0.5"
