[package]
name = "assert_cli"
version = "0.1.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]
repository = "https://github.com/killercup/assert_cli.git"
homepage = "https://github.com/killercup/assert_cli"
license = "MIT"
readme = "README.md"
documentation = "http://killercup.github.io/assert_cli/"
description = "Test CLI Applications."

[features]
default = []
dev = ["clippy"]

[dependencies]
ansi_term = "0.6.3"
difference = "0.4.0"
clippy = {version = "0.0.21", optional = true}
